name: "Dev_pipeline"

on:
  workflow_dispatch:
    branches:
      - dev

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="" -backend-config=config/dev.config
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
 
      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="dev.auto.tfvars"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform apply
        id: apply
        run: terraform apply -var-file="dev.auto.tfvars" --auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}