name: "QA_pipeline"

on:
  workflow_dispatch:
    branches:
      - qa

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=terraform-state-file-7482" -backend-config="prefix=github/terraform-gcp/sandbox"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
 
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var-file="qa.auto.tfvars"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform apply
        id: plan
        run: terraform apply -var-file="qa.auto.tfvars" --auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}