name: "Sample Options"

on:
  workflow_dispatch:
    inputs:
      Environment:
        required: true
        type: choice
        description: "The GCP environment in which the resources will be created"
        options:
          -dev
          -qa
          -prod
      Terraform:
        required: true
        type: choice
        description: "The terraform actions"
        options:
          -apply
          -destroy

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Environment: ${{ github.event.inputs.Environment }}"
        echo "Terraform-Actions: ${{ github.event.inputs.Terraform }}" 
