name: "Sample Options"

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      Environment:
        required: true
        type: choice
        description: "Environment"
        options:
          - dev
          - qa
          - prod
      Terraform:
        required: true
        type: choice
        description: "Terraform Arg"
        options:
          - plan
          - apply
          - destroy
env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=config/${{ github.event.inputs.Environment }}.conf
        
      - name: Terraform Plan
        id: plan
        if: ${{ github.event.inputs.Terraform }} == 'apply'
        run: terraform plan -var-file="${{ github.event.inputs.Environment }}.auto.tfvars"

      - name: Terraform destroy
        if: ${{ github.event.inputs.Terraform }} == 'destroy'
        id: destroy
        run: terraform destroy -var-file="${{ github.event.inputs.Environment }}.auto.tfvars" --auto-approve